apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: playeconomybkm.azurecr.io/play.inventory:1.0.2
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: MongoDbSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: cosmosdb-connectionstring
          - name: ServiceBusSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: identity-secrets
                key: servicebus-connectionstring
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5004
