apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-deployment
spec:
  selector:
    matchLabels:
      app: inventory
  template:
    metadata:
      labels:
        app: inventory
    spec:
      containers:
      - name: inventory
        image: playeconomybkm.azurecr.io/play.inventory:1.0.2
        env:
          - name: ServiceSettings__MessageBroker
            value: SERVICEBUS
          - name: MongoDbSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: inventory-secrets
                key: cosmosdb-connectionstring
          - name: ServiceBusSettings__ConnectionString
            valueFrom:
              secretKeyRef:
                name: inventory-secrets
                key: servicebus-connectionstring
        resources:
          limits:
            memory: "128Mi"
            cpu: "150m"
        ports:
        - containerPort: 5004
        livenessProbe:
          httpGet:
            path: /health/live
            port: 5004
          initialDelaySeconds: 10
        readinessProbe:
          httpGet:
            path: /health/ready
            port: 5004
          initialDelaySeconds: 10
---
apiVersion: v1
kind: Service
metadata:
  name: inventory-service
spec:
  selector:
    app: inventory
  ports:
  - port: 84
    targetPort: 5004
